export const Pages = {
  album: 'album',
  artist: 'artist',
  artistDetail: 'artistDetail',
  category: 'category',
  digital: 'digital',
  digitalAlbum: 'digitalAlbum',
  discover: 'discover',
  fm: 'fm',
  dj: 'dj',
  djHall: 'djHall',
  djRadio: 'djRadio',
  home: 'home',
  migration: 'migration',
  music: 'music',
  mvDetail: 'mvDetail',
  notFound: 'notFound',
  picked: 'picked',
  playlist: 'playlist',
  search: 'search',
  style: 'style',
  topic: 'topic',
  toplist: 'toplist',
  voice: 'voice',
  video: 'video',
  videoDetail: 'videoDetail',
} as const

export type PageName = (typeof Pages)[keyof typeof Pages]
